environment: production

apphost: k8s

deploymenttype: Recreate

label:
    name: pet-store
    
app:
    name: pet-store
    
container:
    name: pet-store
    pullPolicy: Always
    image: swlmicroservicesacr.azurecr.io/pet-store
    tag: latest
    port: 5000
replicas: 1

service:
    port: 8080
    type: ClusterIP

ingress:
    basepath: 