name: Update work item state when PR is merged, opened, closed or when branch is created

on:
   pull_request:
    branches: [ "**" ]
    types: [opened, closed, edited]
   push:
    branches: [ "**" ]

jobs:
  alert:
    runs-on: ubuntu-latest
    name: Changing the task status
    steps:       
    - uses: MarcinGadomski94/pr-update-work-item-state@master
      env: 
        gh_token : '${{ secrets.GH_TOKEN }}'   
        ado_token: '${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}'
        ado_organization: '${{ secrets.ADO_ORGANIZATION }}'
        ado_project: '${{ secrets.ADO_PROJECT }}'
        closedstate: 'Done'
        propenstate: 'Ready'
        inprogressstate: 'In Progress' 
        ghrepo_owner: 'SwapLangauge'
        ghrepo: '<REPO_NAME>'
        pull_number: ${{github.event.number}} 
        branch_name: ${{ github.ref }}
